stages:
  - release

pypi_upload:
  stage: release
  image: python:latest
  script:
    - apt-get -qq update && apt-get -qq install -y protobuf-compiler
    - pip install twine
    - python setup.py sdist bdist_wheel
    - python -m twine upload dist/*
  only:
    - tags
